-- 화면관리
create table JCFIAM_VIEW_RESOURCES
(
  VIEW_RESOURCE_ID    VARCHAR2(16) not null,
  VIEW_RESOURCE_NAME  VARCHAR2(64) not null,
  VIEW_RESOURCE_SEQ   VARCHAR2(3),
  DESCRIPTION         VARCHAR2(512),
  VIEW_RESOURCE_URL   VARCHAR2(128),
  VIEW_RESOURCE_PATTERN   VARCHAR2(128),
  CREATE_DATE         DATE,
  CREATE_USER_ID      VARCHAR2(16),
  LAST_MODIFY_DATE    DATE,
  LAST_MODIFY_USER_ID VARCHAR2(16)
);
-- Create/Recreate primary, unique and foreign key constraints
alter table JCFIAM_VIEW_RESOURCES
  add constraint JCFIAM_VIEW_RESOURCES_PK primary key (VIEW_RESOURCE_ID);