DROP TABLE MEMBER;

CREATE TABLE MEMBER (
	ID INTEGER,
	NAME VARCHAR(50),
	NICKNAME VARCHAR(50),
	ADDRESS VARCHAR(200),
	HOMETOWN VARCHAR(200)
);

INSERT INTO MEMBER (ID, NAME, NICKNAME, ADDRESS, HOMETOWN) VALUES (1, 'NAME1', 'NICK1', 'ADDR1', 'HOME1');
INSERT INTO MEMBER (ID, NAME, NICKNAME, ADDRESS, HOMETOWN) VALUES (2, 'NAME2', 'NICK2', 'ADDR2', 'HOME2');
