DROP SEQUENCE SEQ_KEY IF EXISTS;

CREATE SEQUENCE SEQ_KEY start with 1005 increment by 1;

DROP TABLE PRODUCT_TYPE IF EXISTS;

CREATE TABLE PRODUCT_TYPE(
	PRODUCT_TYPE_ID VARCHAR(20),
	PRODUCT_TYPE_NAME VARCHAR(20),
	PRODUCT_TYPE_DESCRIPTION VARCHAR(400),
	UPDATED TIMESTAMP,
	PRIMARY KEY(PRODUCT_TYPE_ID)
)

DROP TABLE PRODUCT IF EXISTS;

CREATE TABLE PRODUCT(
	PRODUCT_ID INT,
	PRODUCT_TYPE_ID VARCHAR(20),
	PRODUCT_NAME VARCHAR(100),
	PRODUCT_DESCRIPTION VARCHAR(500),
	UPDATED TIMESTAMP,
	PRIMARY KEY(PRODUCT_ID)
);

DROP TABLE PRODUCT_SALES IF EXISTS;

CREATE TABLE PRODUCT_SALES(
	PRODUCT_ID INT,
	SALES_YEAR VARCHAR(10),
	SALES_MONTH VARCHAR(10),
	SALES_QTY INT,
	PRIMARY KEY(PRODUCT_ID, SALES_YEAR, SALES_MONTH)
);

--INSERT INTO PRODUCT_TYPE VALUES('SHT', '선박 타입', '선박 명');

--INSERT INTO PRODUCT VALUES(1001, 'SHT', '살물선', '곡물 ·광석 ·석탄 등을 포장하지 않고 그대로 선창에 싣고 수송하는 화물선', sysdate);
--INSERT INTO PRODUCT VALUES(1002, 'SHT', '유조선', '석유류·경유·당밀·포도주원액·화공약품 및 액화석유가스(LPG)·액화천연가스(LNG) 등 액체화물을 용기에 넣지 않은 비포장 상태로 산적하여 대량수송하는 선박', sysdate);
--INSERT INTO PRODUCT VALUES(1003, 'SHT', '컨테이너선', '컨테이너를 수송하는 선박', sysdate);
--INSERT INTO PRODUCT VALUES(1004, 'SHT', 'FPSO선', 'Floating Production Storage Offloading, 부유식 원유생산저장 설비', sysdate);

